### PR TITLE
QQuickStyle impl

### PR DESCRIPTION
**Pull request by shayanhabibi**
Added setQQuickStyle impl

### CODE REVIEW

**Comment by shayanhabibi** [comment]
added processEvents impl

**Comment by emizzle** [comment]
Thanks for the contribution @shayanhabibi! Would you mind fixing your whitespaces to match the code in the repo? If you look at the diff in the PR, there are diffs that shouldn't be there, likely because of whitespaces.

**Comment by emizzle** [comment]
Also, purely out of curiosity (and for completeness of this PR description), why do you need QQuickStyle?

**Comment by shayanhabibi** [comment]
Will handle that.
I'm using QQuickStyle for rapid prototyping and back-end focus. I was finding it difficult using config, and environment commands to maintain the style when deployed without needing voodoo; this was fixed easily by setting the QQuickStyle and it just looks a lot nicer and simpler to me.

**Comment by emizzle** [comment]
@shayanhabibi -- were you meaning to send a PR to the original repo? This is a fork of the original repo https://github.com/filcuc/nimqml.

**Comment by shayanhabibi** [comment]
I was intending to contribute to your fork as your upstream work is essential to distributable ready work, however I can see from further work with your fork and exploration through your client that this PR wouldn't be very beneficial in the use case of your project.

It is unfortunate as I would determine that the up-stream work that status has done for nimqml is very beneficial and is maintained more regularly.

**Pull request closed without merging**
